# docker-compose.yml
version: '3.8'

services:
  dr-copilot:
    build: .
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./model:/app/model
      - ./static:/app/static
    restart: unless-stopped